x = int(input("enter in x:"))
y = int(input("enter in y:"))
z = int(input("enter in z:"))
n = int(input("enter in n:"))
print([[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if (i+j+k)!=n])
